<?php

namespace Plugin\ShoppingMall\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\ShoppingMall\Entity\ShoppingMallConfig;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ShoppingMall Config
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoppingMallConfigRepository extends AbstractRepository
{
    /**
     * ShoppingMallConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, ShoppingMallConfig::class);
    }

    /**
     * @param int $id
     *
     * @return ShoppingMallConfig|null
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
